// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.donation.eoy.version.viewed", 4);
user_pref("app.update.auto.migrated", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1705778112);
user_pref("app.update.lastUpdateTime.background-update-timer", 1705778112);
user_pref("app.update.lastUpdateTime.region-update-timer", 1705778112);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1705778112);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1705052249);
user_pref("app.update.lastUpdateTime.telemetry_untrustedmodules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1705778112);
user_pref("app.update.migrated.updateDir3.D78BF5DD33499EC2", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.region.update.updated", 1705778112);
user_pref("browser.search.region", "US");
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("calendar.caldav.googleResync", 1705052190);
user_pref("calendar.list.sortOrder", "ba50e454-650d-4d01-8d65-ff5e80ce2fac");
user_pref("calendar.registry.ba50e454-650d-4d01-8d65-ff5e80ce2fac.calendar-main-default", true);
user_pref("calendar.registry.ba50e454-650d-4d01-8d65-ff5e80ce2fac.calendar-main-in-composite", true);
user_pref("calendar.registry.ba50e454-650d-4d01-8d65-ff5e80ce2fac.disabled", true);
user_pref("calendar.registry.ba50e454-650d-4d01-8d65-ff5e80ce2fac.name", "Home");
user_pref("calendar.registry.ba50e454-650d-4d01-8d65-ff5e80ce2fac.type", "storage");
user_pref("calendar.registry.ba50e454-650d-4d01-8d65-ff5e80ce2fac.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "America/Los_Angeles");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1705052199898");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1705778112);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20240105183125");
user_pref("extensions.lastAppVersion", "115.6.1");
user_pref("extensions.lastPlatformVersion", "115.6.0");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"38067450-5d60-4db1-9606-508dfc77f432\",\"google@search.mozilla.org\":\"20959ba1-97b9-4083-964b-e53e4a1bbd06\",\"ddg@search.mozilla.org\":\"81e85019-87af-4790-b7b2-c3cf00a62d1f\",\"amazondotcom@search.mozilla.org\":\"946be4ed-d671-4560-af07-05932ac195e3\",\"wikipedia@search.mozilla.org\":\"7b3f1de5-5256-4b3e-81b9-a8409d9e1392\",\"bing@search.mozilla.org\":\"e35f129d-8497-47bc-9e08-39976e95e616\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx-shader-check.build-version", "20240105183125");
user_pref("gfx-shader-check.device-id", "0x1f14");
user_pref("gfx-shader-check.driver-version", "31.0.15.3640");
user_pref("gfx-shader-check.ptr-size", 8);
user_pref("idle.lastDailyNotification", 1705778193);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.e2ee.auto_enable", true);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.rights.version", 1);
user_pref("mail.spam.logging.enabled", true);
user_pref("mail.spam.manualMark", true);
user_pref("mail.spam.markAsReadOnSpam", true);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 40);
user_pref("mailnews.database.global.datastore.id", "744ed038-02e0-4681-b807-72d6d9a6590");
user_pref("mailnews.downloadToTempFile", true);
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.6.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.cookieBehavior", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1705349082);
user_pref("places.history.enabled", false);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1705778193136");
user_pref("sanity-test.device-id", "0x1f14");
user_pref("sanity-test.driver-version", "31.0.15.3640");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20240105183125");
user_pref("services.settings.clock_skew_seconds", -18199);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1705796313);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1705796313);
user_pref("services.settings.thunderbird.search-config.last_check", 1705796313);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1705796313);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1705349082);
user_pref("toolkit.startup.last_success", 1705778080);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20240105183125");
